### ISSUE TITLE
CT issues for May 3, 2020

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#1035]
I'd like to have a better understanding of the issues on CT today.  If there are pre-existing issues, I'll mark them below.  If I can't find them, I'll create them.

On second thought, let's start with a checklist in case any can be closed quickly.

- [x] Balancing Act/Color Vision/Natural Selection:  Uncaught Error: The specified studio instance should be selected
- [ ] Balloons and Static Electricity: Assertion failed: induced charge did not change since last description, 
- [x] BASE unit tests: this.callback is not a function
- [ ] Blackbody Spectrum: Uncaught Error: Assertion failed: Impossible set state from iterate:.  Likely will be initially addressed by https://github.com/phetsims/phet-io/issues/1635
- [ ] Build an Atom: parent should not have child: nucleons
- [ ] Circuit Construction Kit suite: parent should not have child: resistorNode
- [x] Density and Buoyancy Common: 0 out of 0 tests passed. 0 failed.
- [ ] Energy Skate Park: 6. Any static, registered PhetioObject can never be deregistered.  Likely will be initially addressed by https://github.com/phetsims/phet-io/issues/1635
- [x] Faradays Law: 0 out of 0 tests passed. 0 failed.
- [ ] Number Line Suite: Cannot read property 'valueToModelPosition' of undefined https://github.com/phetsims/number-line-integers/issues/98
- [ ] Scenery-phet tests: Cannot read property 'dataStream' of undefined, see https://github.com/phetsims/scenery-phet/issues/602
- [ ] Studio: 0 out of 0 tests passed. 0 failed.  SR: Working on my local copy.
- [x] Tandem unit tests: Assertion failed: instance should be marked as phetioDynamicElement:true

**Comment by samreid** [comment]
Let's track in other issues now, closing.
