### ISSUE TITLE
Convert common code to Typescript

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#1096]
Devs- JO(20), JG(20), CM(20), JB(40), SR(40), CK(20), MK(8) 

*Design Pattern work happens ahead of this work

### Priority
Proactive conversions
- [x] Options/Merge 
- [x]  Scenery - JO(), JG()
- [x]  Scenery-PhET - CM(), Other devs based upon what conversions are identified   (https://github.com/phetsims/scenery-phet/issues/726 for continuation)
- [x] Sun - JB(), Other devs based upon what conversions are identified
- [ ] PhET-Core -
- [x] Tambo - JB
- [ ] Tandem
- [ ] Axon
- [ ] Joist - MK Priority for sim facing items
- [ ]  https://github.com/phetsims/simula-rasa/issues/21 - CM() 
10. Review Sims that are in TS and convert CC based upon these as priorities
11. Create a ranked list 

**scenery-phet items in typescript sims:**

<details>
[
    "TimeSpeed.js",
    "PhetFont.js",
    "ArrowNode.js",
    "MeasuringTapeNode.js",
    "PhetColorScheme.js",
    "ResetAllButton.js",
    "RestartButton.js",
    "TimeControlNode.js",
    "StopwatchNode.js",
    "NumberControl.js",
    "ArrowShape.js",
    "KeyboardHelpSection.js",
    "TextKeyNode.js",
    "RulerNode.js",
    "MagnifyingGlassZoomButtonGroup.js",
    "SceneryPhetConstants.js",
    "sceneryPhetStrings.js",
    "LetterKeyNode.js",
    "NumberKeyNode.js",
    "ArrowKeyNode.js",
    "NumberPicker.js",
    "LockNode.js",
    "NumberDisplay.js",
    "WireNode.js",
    "Alerter.js",
    "MathSymbols.js",
    "ThermometerNode.js",
    "ShadedSphereNode.js",
    "MultiLineText.js",
    "WavelengthSpectrumNode.js",
    "FaceNode.js",
    "StarNode.js",
    "PlayIconShape.js"
]
</details>

### sun items in typescript sims:

<details>
[
    "HSlider.js",
    "Checkbox.js",
    "HSeparator.js",
    "TextPushButton.js",
    "Panel.js",
    "AquaRadioButton.js",
    "RectangularRadioButtonGroup.js",
    "RectangularPushButton.js",
    "VSlider.js",
    "AccessibleSlider.js",
    "AccordionBox.js",
    "ComboBox.js",
    "ComboBoxItem.js",
    "ToggleNode.js",
    "AquaRadioButtonGroup.js",
    "VerticalAquaRadioButtonGroup.js",
    "VSeparator.js",
    "BooleanRoundToggleButton.js",
    "VerticalCheckboxGroup.js",
    "ABSwitch.js",
    "ArrowButton.js",
    "ClosestDragListener.js",
    "Carousel.js",
    "Dialog.js"
]
</details>

### scenery items in any typescript file:

<details>
[
    "Line",
    "Node",
    "PAINTABLE_DEFAULT_OPTIONS",
    "Rectangle",
    "Color",
    "CanvasNode",
    "Path",
    "LayoutBox",
    "Text",
    "VBox",
    "HBox",
    "RichText",
    "DragListener",
    "Utils",
    "LinearGradient",
    "NodeOptions",
    "NodeProperty",
    "SimpleDragHandler",
    "Image",
    "SceneryEvent",
    "Trail",
    "WebGLNode",
    "ShaderProgram",
    "HStrut",
    "Circle",
    "VStrut",
    "AlignGroup",
    "KeyboardUtils",
    "AlignBox",
    "FireListener",
    "Gradient",
    "ProfileColorProperty",
    "Font",
    "KeyboardDragListener",
    "ColorDef",
    "FocusHighlightFromNode",
    "SceneryConstants",
    "colorProfileProperty",
    "scenery",
    "PathOptions",
    "ColorProperty",
    "Pointer",
    "voicingManager",
    "FocusHighlightPath",
    "Voicing",
    "globalKeyStateTracker",
    "ParallelDOM",
    "PDOMPeer",
    "HeightSizable",
    "WidthSizable"
]

</details>

**Comment by pixelzoom** [comment]
My few experiences converting common-code to TS have been (mostly) smooth.  The one thing I bump into all the time is how to handle options.

For example, AquaRadioButtonGroup is a subclass of LayoutBox, so conversion should look like:

```js
type AquaRadioButtonGroupOptions = Omit< LayoutBoxOptions, 'children' >;

class AquaRadioButtonGroup<T> extends LayoutBox {
`

But LayoutBox has not been converted to TS, and LayoutBoxOptions does not exist.   So I did this in the meantime:

```js
//TODO https://github.com/phetsims/chipper/issues/1128 replace any with LayoutBoxOptions, when it exists
type AquaRadioButtonGroupOptions = Omit< any, 'children' >;
```

So it seems like we should give highest priority to converting more sim-facing scenery types.

**Comment by zepumph** [comment]
Yes understood, in the quarterly goals we decided that https://github.com/phetsims/tasks/issues/1097 was a precursor to this issue. I marked https://github.com/phetsims/chipper/issues/1128 as high priority to try to unblock these conversions as quickly as possible.

**Comment by chrisklus** [comment]
From 1/27/22 dev meeting: We checked in on this and @zepumph recommended we hold off until more Design Pattern work (like options patterns) is completed. We're thinking ~3 weeks will be a good timeline.

**Comment by zepumph** [comment]
`IntentionalAny.ts` was added based on a conversation in slack. Any presence of `any` in the project will be considered suspect.

**Comment by zepumph** [comment]
Using it in some mixins above.

**Comment by samreid** [comment]
IntentionalAny has been working great, thanks!

**Comment by zepumph** [comment]
From today's typescript conversion:

SR: It has been helpful for me to convert common code as I run into it while developing my sims.

We will create an issue to convert Dialog and Popupable.

Status of conversion in lines of code:
scenery-phet JS: 13958 total, TS 12622 total
sun: 878 JS, 13484 TS
scenery: 37918 JS, 45377 TS
axon: 2823 JS, 5032 TS
joist: 7446 JS, 5736 TS


We are not complete with TS conversion, but this issue has run it's course. We are calling this sprint complete, and are ready to close.
