### ISSUE TITLE
Liam Checklist

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#1122]
# Employee/Affiliate Leaving Checklist

## Responsibilities of Departing Employee
- [x] Submit your letter of resignation to supervisor.
- [ ] Ensure your address is up to date in myCUinfo. This ensures you will receive your W-2 in a timely manner.
- [x] Inform committees/team you are working on of your resignation.
- [x] Submit final my.leave timesheet as soon as possible (once your last day is finalized)

### Turn in all university property to Physics department or PhET:
- [x] Door Keys. If needed, can be mailed to:
Facilities Management Access Services
University of Colorado Boulder
UCB 53
Boulder, CO 80309
- [x] Buff OneCard and Eco Pass
- [x] A-Card or US Bank Cards
- [x] Library materials
- [x] Departmental property such as computers, and related peripherals (monitors, keyboards)
- [x] Petty cash
- [x] Parking permits and gate cards

### Files and access:
- [ ] Pass on any necessary external account administration/credential information.
- [ ] Ensure PhET digital files are stored in 'PhET Files'.

## Internal (PhET) Administrative Responsibilities
- [ ] Exit Interview if appropriate
- [x] Buff One card, Eco-Pass returned via campus mail to 159 UCB or in person at the Campus Card Office located at Center for Community (C4C), Room N180, 159 UCB
- [x] Final payment submitted
- [x] Pay up to max of vacation at separation, VCT  for resignation. Prorated leave accruals until last day worked and pay out vacation. 'CUES_HCM_LEAVE_ACCRUAL_SUM - Leave Accrual Summary', departing employee signs, attached to VCT transaction.
- [x] Termination in HCM. Termination effective date in HCM (5/27) is the following day after last day worked.

### Accounts
- [x] Remove from PhET google group
- [x] Remove GitHub access
- [x] Remove from Slack
- [x] Remove admin access on website
- [x] Remove from About Page
