### ISSUE TITLE
Emily Checklist

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tasks#1125]
# Employee/Affiliate Leaving Checklist

## Responsibilities of Departing Employee
- [ ] Submit your letter of resignation to supervisor.
- [ ] Ensure your address is up to date in myCUinfo. This ensures you will receive your W-2 in a timely manner.
- [ ] Inform committees/team you are working on of your resignation.
- [ ] Submit final my.leave timesheet as soon as possible (once your last day is finalized)

### Turn in all university property to Physics department or PhET:
- [ ] Departmental property such as computers, and related peripherals (monitors, keyboards)

### Files and access:
- [ ] Pass on any necessary external account administration/credential information.
- [ ] Ensure PhET digital files are stored in 'PhET Files'.

## Internal (PhET) Administrative Responsibilities
- [ ] Exit Interview if appropriate
- [ ] Buff One card, Eco-Pass returned via campus mail to 159 UCB or in person at the Campus Card Office located at Center for Community (C4C), Room N180, 159 UCB
- [ ] Send copy of final leave balance sheet to HR 565UCB
- [ ] (if applicable) Cancel PSC cards (procurement/travel card)
- [ ] Final payment submitted
- [ ] Pay up to max of vacation at separation, VCT  for resignation. Prorated leave accruals until last day worked and pay out vacation. 'CUES_HCM_LEAVE_ACCRUAL_SUM - Leave Accrual Summary', departing employee signs, attached to VCT transaction.
- [ ] Termination in HCM. Termination effective date in HCM is the following day after last day worked.

### Accounts
- [ ] Remove from PhET google group
- [ ] Remove GitHub access
- [ ] Remove from Slack
- [ ] (if applicable) Remove unfuddle access
- [ ] (if applicable) Cancel A-Card or US Bank Cards
- [ ] Remove admin access on website
- [ ] Remove from About Page
