### ISSUE TITLE
"todo-should-have-issue" lint rule should be turned on in more places 

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#1128]
Since https://github.com/phetsims/chipper/issues/946, were we looped a side-effect feature into the "todo-should-have-issue" lint rule to reopen closed github issues, this rule has gotten more important. We should take another pass at turning this on in as much common code as possible. For examples, phet-io-sim-specific only has a few TODOs, let's get some issues on those!

**Comment by zepumph** [comment]
Currently there are 83 usages of `todo-should-have-issue": "off"` in these repos.

<details>

```
aqua
area-builder
area-model-common
balancing-act
bending-light
build-an-atom
capacitor-lab-basics
charges-and-fields
circuit-construction-kit-black-box-study
circuit-construction-kit-common
color-vision
coulombs-law
density-buoyancy-common
dot
eating-exercise-and-energy
estimation
faradays-law
fenster
fluid-pressure-and-flow
forces-and-motion-basics
fraction-comparison
interaction-dashboard
inverse-square-law-common
john-travoltage
kite
least-squares-regression
models-of-the-hydrogen-atom
molecule-shapes
my-solar-system
normal-modes
optics-lab
phet-io-sim-specific
phet-io-test-sim
phet-io-wrapper-lab-book
phet-io-wrappers
quadrilateral
quake
rutherford-scattering
scenery
shred
solar-system-common
sound-waves
tappi
xray-diffraction
yotta
```

</details>

Here are the ones that feel important to me:

- [ ] aqua
- [ ] dot
- [ ] kite
- [ ] phet-io-sim-specific
- [ ] phet-io-test-sim
- [ ] phet-io-wrappers
- [ ] scenery

**Comment by zepumph** [comment]
@samreid would like to try to use AI to solve this busy work.

**Comment by samreid** [comment]
There are 904 TODOs without issues. Do we want issues for all of those?

**Comment by zepumph** [comment]
How about an issue per repo? So 41 repos.

"That's a great idea"
-SR

**Comment by zepumph** [comment]
We can definitely make 41 issues to hold TODOs: one per repo, but I thought I would just make this issue happen with a lint rule fixer always pointing to a central issue (https://github.com/phetsims/tasks/issues/1129).

To me I'm most excited to get all issues reopened if they still have TODOs, no matter the repo, so this "workaround" all pointing to 1129 doesn't seem too bad to me. I'll be interested to see what get's reopened tonight. 


https://github.com/phetsims/chipper/blob/0dd1176437daea5cfc136aa12091092190ed11c3/eslint/rules/todo-should-have-issue.js#L62-L84


This was a very helpful link: https://eslint.org/docs/latest/extend/custom-rules#applying-fixes


@samreid what are you thinking over here?

**Comment by zepumph** [comment]
Looks like 6 issues were reopened last night. Yay!
https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aphetsims+%22Reopening+because+there+is+a+TODO+marked+for+this+issue.%22+sort%3Aupdated-desc

![image](https://github.com/phetsims/tasks/assets/6856943/d3f751dd-b422-4fce-98e6-1fde5ca21e57)

**Comment by samreid** [comment]
That's great, thanks! I also considered that a central issue would be a good step to get this rule enabled. Some remaining steps for discussion:
* There are a few files that are still opting out of that rule, let's see if we can remove it there too. Namely .eslintrc.js.  I'm not concerned about the 1 occurrence in handlePlaybackEvent_2.0.js. Or the occurrences in the rule itself.
* Also, I have observed that at least one PhET developer has "run eslint --fix on file save" in their eslint settings. I think that could result in unexpected autofixes for new issues. So I'm considering that having that as an autofix for the batch above was great, but maybe we should remove the autofix for going forward?  Let's discuss.

**Comment by zepumph** [comment]
- [ ] Remove the auto fix. 
- [ ] Unpublished sims with very little development should have this rule turned off again:
  - [ ] MOTHA
  - [ ] Buoyancy
  - [ ] tappi
  - [ ] fenster
- [ ] keplers-laws - issue per TODO please


"Non-production code" even in common code, can opt out of this via a `.eslintrc` in a sub-directory.

**Comment by zepumph** [comment]
I'll keep working on this once @pixelzoom does the sims he would like to take care of. Sorry for the trouble!

**Comment by pixelzoom** [comment]
I completed work over in https://github.com/phetsims/tasks/issues/1129.  Back to @zepumph.

**Comment by zepumph** [comment]
Fixer removed above, if we ever want it back, here it is. It was my first fixer I wrote, so I could imagine coming back here for inspiration.


<details>

```js
{fix: fixer => {

                    const range = comment.range;
                    let insertionSpot = range[ 1 ];
                    if ( comment.type === 'Block' ) {
                      const match = comment.value.match( /TODO(.*\r)*\n/ );

                      // no match would be something like function( /* is this thing on */ ), so at the end is fine
                      if ( match ) {
                        const lengthToEndOfTODOLine = match.index + match[ 0 ].length;

                        // Set the end range to just after the line with a to-do
                        insertionSpot = range[ 0 ] + lengthToEndOfTODOLine;
                      }
                      else {
                        // no match would be something like function( /* is this thing on */ ), so at the end minus closing comment
                        insertionSpot -= 3;
                      }
                    }

                    // a central issue to hold all TODOs
                    return fixer.replaceTextRange( [ insertionSpot, insertionSpot + 1 ], ' https://github.com/phetsims/tasks/issues/1129' );
                  }}
```

**Comment by zepumph** [comment]
There are now only 189 TODOs pointing to https://github.com/phetsims/tasks/issues/1129 all of which are in simulation code instead of common code, and it feels much more organized to me. I will continue with https://github.com/phetsims/chipper/issues/1403. Closing
