### ISSUE TITLE
One issue to hold every TODO in the project

### ISSUE THREAD

**Issue by zepumph** [phetsims/tasks#1129]
From https://github.com/phetsims/tasks/issues/1128, it will be a good starting point if every TODO that doesn't currently have an issue assigned to it, points to this issue instead. Then we will get the benefits of having closed issues reopened when TODOs point there for all repos.

**Comment by zepumph** [comment]
There are currently 890 TODOs pointing to this issue. Fun!

**Comment by pixelzoom** [comment]
I did a lot of work to eliminate references to this issue.

There were a number of places where a link to this issue was errorneously added, because the issue was not on the same line as "TODO".  In those cases, I simply removed the reference to those issues.  For example in MagnetRegionManager:

```
    // TODO: The code below looks wrong.  The return type doesn't match the header docs, and the whole thing is too https://github.com/phetsims/tasks/issues/1129
    //  tightly coupled to the way bounds are managed in the model.  See
    // https://github.com/phetsims/faradays-law/issues/164. Also, it seems like it should return null instead of -1 if
    // no intersection is found.
```

In these repos, there were a small number of TODOs, so I created specific GitHub issues:

* aqua
* balloons-and-static-electricity
* color-vision
* faradays-law
* inverse-square-law-common
* least-squares-regression
* normal-modes
* optics-lab
* rutherford-scattering
* shred
* xray-diffusion

In these repos, I created one repo-specific "Address TODOs" issue:

* area-builder
* balancing-act
* build-an-atom
* bending-light
* capacitor-lab-basics
* charges-and-fields
* coulombs-law
* sound-waves

Sim repos that continue to point to this issue:

- [ ] cck-black-box-study (23)
- [ ] cck-common (9)
- [ ] density-buoyancy-common (27)
- [ ] eating-and-exercise-energy (8)
- [ ] estimation (2)
- [ ] fluid-pressure-and-flow (30)
- [ ] forces-and-motion-basics (32)
- [ ] fraction-comparison (5)
- [ ] molecule-shapes (12)

Common-code repos that continue to point to this issue. dot, kite, and scenery are the obvious problems here.

- [ ] dot (45)
- [ ] interaction-dashboard (5)
- [ ] kite (75)
- [ ] phet-io-test-sim (6)
- [ ] phet-io-wrapper-lab-book (20)
- [ ] quake (1)
- [ ] scenery (325)
- [ ] tappi (4)

**Comment by pixelzoom** [comment]
Back to @zepumph to continue work on this issue. 

Regarding the errorneous TODOs identified by the lint rule... In Slack#DM, @zepumph said:
> Yes I think we could adapt our rule to support that. Could you make an issue in chipper please? It is because eslint thinks of a single "comment" only as one line comment or one block comment. It doesn't combine those. I hadn't seen that case before but obviously we want to support that (I certainly write TODOs like that).

**Comment by zepumph** [comment]
After the above work, there are 189 TODOs pointing to this issue. That is better than 890! @pixelzoom did a good job of outlining where they live right now. I'm going to unassign for now. Thanks all.
