### ISSUE TITLE
Create a S2015R checklist

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#291]
In https://github.com/phetsims/sherpa/issues/37, @ariel-phet suggested creating a S2015R checklist.  

@ariel-phet said:

Perhaps lets make a sample list here and then put it in phet-info when ready?

@samreid - thoughts/addition/clarifications to the list below?

- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over @pixelzoom's revamped code review checklist 
- [ ] Review and update licensing info (source code and images/audio)
- [ ] Any sort of translation beta test necessary?
- [ ] Perform RC testing
 - [ ] Include full screen test
- [ ] Address RC issues and publish
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by samreid** [comment]
@pixelzoom also suggested the following:

Since the focus of this redeploy is translations, I'd like to see the "translation beta test" item fleshed out a bit more.  Perhaps:

- [ ] stringTest=double
- [ ] stringTest=X
- [ ] stringTest=SomeExtremelyLongStringThatWouldLikelyBreakAnythingThatDoubleDidNotExpose
- [ ] Rosetta test (whatever that is)
- [ ] RTL language test

**Comment by samreid** [comment]
Assigned to @samreid since @ariel-phet requested feedback for the list.

**Comment by samreid** [comment]
I've made some suggestions during the meeting, but my other thought is to also include our normal QA/deploy checklists, such as https://github.com/phetsims/tasks/blob/master/doc/issue-template-release-candidate-testing.md and some of the lists from https://github.com/phetsims/phet-info/

**Comment by ariel-phet** [comment]
Probably after first redeployed sim, do beta testing of rosetta deploying to phet-dev. Then after all working allow depolys to figaro.

**Comment by ariel-phet** [comment]
- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over @pixelzoom's revamped code review checklist 
- [ ] Review and update licensing info (source code and images/audio)
- [ ] stringTest=SomeExtremelyLongStringThatWouldLikelyBreakAnythingThatDoubleDidNotExpose
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] RTL language test
- [ ] Perform RC testing
 - [ ] Include full screen test
- [ ] Address RC issues and publish
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by ariel-phet** [comment]
Moved to https://github.com/phetsims/tasks/blob/master/doc/S2015R_checklist.md

Closing
