### ISSUE TITLE
Fall 2015 PhET office moving checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tasks#337]
- [x] Remove Blackboards
- [x] Scrape away blackboard adhesive
- [x] Sand adhesive, and patch holes
- [x] Arrange for paint touch up
- [x] Re-key offices
- [x] Purchase new whiteboards (same brand, with magnetic backing)
- [x] Install new whiteboards
- [x] Furniture layout for each office
- [x] Arrange move-in with undergrad assistance

Current plan is:
-- Developers in the corner office (3 desks, 1 "floaty" desk for Aaron/Jesse)
-- Amy H / Amy R desks with spare table, in next office over
-- Amanda, Susan (starting in spring), and Trish's desk in next office over
-- (Phase 2) Testing desk/bookshelf, and 2 work tables for undergrads in Bolton's office
-- Emily/Oliver/Arnab in Oliver's office.

**Comment by amanda-phet** [comment]
I would like one of the small wood-laminate desks, a chair, and a bookshelf. The desk and chair I'm currently using are working well for me, so I'll continue using those. The bookshelves downstairs are fine, but if we're moving the green ones down I'll take a green one.

**Comment by ariel-phet** [comment]
@arouinfar and @amyh-phet please comment in this issue what you would like in your office. Thanks!

**Comment by amyh-phet** [comment]
I definitely would like the desk and chair I currently use.   It also sounds like the table and extra office chairs should come too.  I will check with Amy R on Monday to figure out any other items that should be moved.

**Comment by arouinfar** [comment]
I would also like to keep my current desk and chair.  @amyh-phet and I will discuss what other furniture we'd like moved over on Monday and let you know, @ariel-phet.

**Comment by amanda-phet** [comment]
Trish wants her current table, bookshelf, and chair.

**Comment by jbphet** [comment]
I'd like the tall wooden bookshelf, the larger black office chair, my stand-up desk apparatus, the books on the back of my desk, the Gateway PC tower (phet-server) to the left of my desk, the UPS next to phet-server, to all be moved.  The large green steel desk should NOT be moved (one of the drawers doesn't close), and the bookshelf sort of thing at the back of it should also NOT be moved.  I may use the desk that's currently in the new office, but I'm looking at some other options, so that may change.

The refrigerator that is currently in my office should be moved to the 9th floor to whichever office makes the most sense.  Another office may be better, since there are going to be three desks in the new office, but whatever works.

The gray steel file cabinet should not be moved.  There are some files and some power supplies in it - I'm not sure who should sort through those, but someone probably should.

I think @ariel-phet is already working on the whiteboards, so I think they are NOT being moved.

**Comment by arouinfar** [comment]
After discussion with @amyh-phet we've decide to keep the two bookcases and chair currently in the new office, but get rid of the desk and large table. We'd also like to move our desks, all of the chairs, and the large table from F-1019. There are three large green bookcases in our office that do NOT need to be moved (unless @emily-phet wants one for her new office).

**Comment by ariel-phet** [comment]
Phase 1 complete, closing
