### ISSUE TITLE
RC test: Molarity 1.2.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#390]

**Comment by pixelzoom** [comment]
Checklist for S2015R milestone (GitHub issues labeled "Summer 2015 redeploy")

**Developer**
- [ ] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [ ] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [ ] Review and update licensing info (source code and images/audio)
  - [ ] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [ ] Standardize the string keys, since they will be difficult to change later
- [ ] Identify any strings in sims that should move to another repository, move them now
- [ ] Publish RC version and test matrix
- [ ] Address RC issues and publish

**QA**
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] Perform RC testing
 - [ ] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by pixelzoom** [comment]
Test matrix:
https://docs.google.com/spreadsheets/d/1TGckOBNmvdCQvuHQCZ0hK5mOfAU_WdidNbirI24DJI0/edit#gid=2010012600

Links to the RC version are provided in the test matrix (upper left).

I spot tested on the following platforms:
• iPad2 + iOS 9.0.2 + Safari
• Mac Pro + OS X 10.10.5 + Safari
• Mac Pro + OS X 10.10.5 + Chrome
• Mac Pro + OS X 10.10.5 + Firefox

In addition to completing the test matrix and QA check list (shown above), please verify the following issues that were identified in the previous release candidate. If any of these fails verification, reopen and add troubleshooting information.

- [ ] https://github.com/phetsims/molarity/issues/21 (long string test)
- [ ] https://github.com/phetsims/molarity/issues/22 (Concentration scaled down)
- [ ] https://github.com/phetsims/molarity/issues/23 (add QA credits)
- [ ] https://github.com/phetsims/molarity/issues/24 (Issues with text rendering on Edge)

**Comment by pixelzoom** [comment]
@ariel-phet Ready for RC testing.

**Comment by ariel-phet** [comment]
@elisemorgan @bryo5363 @orejolaphet @arnabp @phet-steele @amyh-phet 

**Please make this sim top testing priority**

 we want to move this testing along efficiently so for instance @arnabp and @amyh-phet if you have some time tomorrow please hop in on some platforms.

Many common code changes have occurred since the last RC. These changes have been spotted checked, but please test thoroughly on all platforms as this RC is serving as a benchmark for if our current code base is stable.

**Comment by ariel-phet** [comment]
I performed stringTests on chrome on windows, all appeared normal

**Comment by elisemorgan** [comment]
@ariel-phet If no one has done Win 8 by this afternoon, is it ok for me to test this RC on Socrates?

**Comment by ariel-phet** [comment]
@elisemorgan, Yes, that should be alright for this sim.

**Comment by amyh-phet** [comment]
@elisemorgan  I can test Win 8 on my laptop this morning.   Can you test Win 10?

**Comment by ariel-phet** [comment]
@oliver-phet can you make the (somewhat crappy) windows 10 computer available for testers until we get the JB computer swap worked out?

**Comment by amyh-phet** [comment]
@ariel-phet  if needed i can upgrade to Win 10 on my laptop if other computers can run Win 8.

**Comment by elisemorgan** [comment]
@amyh-phet I don't have access to a Win 10 device but I can test on Win 8. So an upgrade on your device would be most convenient. Thanks for your help!

**Comment by oliver-phet** [comment]
Win 10 computer has been added to the asset inventory (still needs label and name) and put in F1011.

**Comment by ariel-phet** [comment]
@amyh-phet stay on win 8 for the moment. We need to do a bit of device musical chairs, and now we have a win 10 computer in the testing office

**Comment by elisemorgan** [comment]
@ariel-phet All platforms have been tested

**Comment by ariel-phet** [comment]
@elisemorgan can you look at the two remaining checkbox's? I have checked an iframe and it looked good. Can you test that and text rendering on edge? (I assume good since you saw no issues)

**Comment by amyh-phet** [comment]
@ariel-phet   Will stay on Win 8

**Comment by elisemorgan** [comment]
@pixelzoom phetsims/scenery#464 was reproducible. See phetsims/hookes-law#32

**Comment by pixelzoom** [comment]
@elisemorgan OK, thanks.

**Comment by pixelzoom** [comment]
Dev meeting decision: We will publish this with the iframe problem (phetsims/scenery#464), since it's better than what's currently on the website.

**Comment by pixelzoom** [comment]
RC test complete and passed. Thanks everyone. Onward to 1.0.0.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet to complete checklist items in https://github.com/phetsims/tasks/issues/390#issuecomment-148214213.
