### ISSUE TITLE
RC test: Hooke's Law 1.0.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#392]
Checklist for S2015R milestone (GitHub issues labeled "Summer 2015 redeploy")

**Developer**
- [x] Review outstanding issues, mark what will be addressed for redeploy (@ariel-phet and original developer). Then mark these issues with a milestone.
- [x] Look over the code review checklist, decide if code review should be redone, https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md
- [x] Review and update licensing info (source code and images/audio)
  - [x] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md
- [x] Standardize the string keys, since they will be difficult to change later
- [x] Identify any strings in sims that should move to another repository, move them now
- [x] Publish RC version and test matrix
- [x] Address RC issues and publish

**QA**
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] Perform RC testing
 - [x] Include full screen test

**Design/Admin**
- [ ] Rosetta test (Opening sim to trusted translators for beta)
- [x] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [ ] Review process with QA team.

**Comment by pixelzoom** [comment]
Test matrix:
https://docs.google.com/spreadsheets/d/1nXLDYtyugguh2kG23atx9zwECCGEtk-Pbs2Gj27e8vc/edit#gid=464137285

Links to the RC version are in the test matrix (upper left).

I spot tested on the following platforms:
• Mac Pro + OS X 10.10.5 + Safari
• Mac Pro + OS X 10.10.5 + Chrome
• Mac Pro + OS X 10.10.5 + Firefox

In addition to completing the test matrix and QA check list (shown above), please verify the following issues that were identified in the previous release candidate:

- [ ] https://github.com/phetsims/hookes-law/issues/26 (fix QA credits)
- [ ] https://github.com/phetsims/hookes-law/issues/27 (i18n issue with vectors)
- [ ] https://github.com/phetsims/hookes-law/issues/29 (i18n of panels containing sliders)
- [ ] https://github.com/phetsims/hookes-law/issues/30 (overlap of Series springs on Systems screen)

Also verify these common-code issues:

- [ ] phetsims/scenery#464 (fix for iframe)
- [ ] https://github.com/phetsims/beers-law-lab/issues/112 (potential performance problem with iframe fix)
- [ ] phetsims/molarity#24 (Issues with text rendering on Edge)

If any of the above issues fails verification, reopen and add troubleshooting information.

**Comment by pixelzoom** [comment]
@ariel-phet Ready for RC testing.

**Comment by ariel-phet** [comment]
@elisemorgan @amyh-phet @arouinfar @bryo5363 @orejolaphet @phet-steele @bryo5363 

Please make this sim the top testing priority once Molarity is finished up (looks like only a few platforms to go on that one)

**Comment by ariel-phet** [comment]
I performed all string tests and multiple full screen tests. All looks good.

**Comment by elisemorgan** [comment]
@ariel-phet All major platforms have been tested

**Comment by ariel-phet** [comment]
Excellent, thanks @elisemorgan! Closing

**Comment by pixelzoom** [comment]
Reopening. Please describe the next step.  Fix any issues? Another RC? Publish as is? ...

**Comment by aaronsamuel137** [comment]
@ariel-phet asked me to publish this to the website this morning. I am planning on doing so around 9AM.

**Comment by pixelzoom** [comment]
Thanks @aaronsamuel137. Closing.

**Comment by pixelzoom** [comment]
Reopening again. @ariel-phet There are incompletely items in the Design/Admin section of the publishing checklist (see above) and I don't see any related issues for addressing those.

**Comment by arouinfar** [comment]
@pixelzoom I've spoken to @ariel-phet directly about this yesterday. I am prepared to enter the necessary information on the website once @aaronsamuel137 publishes.

**Comment by arouinfar** [comment]
The Teacher Tips document is ready to upload. There are currently several other sim primers in the production stage, and the recording mic is being revisited for future primers (including Hooke's Law). It will be awhile before a Hooke's Law primer can be released.

**Comment by ariel-phet** [comment]
@pixelzoom - remaining items being tracked here now https://github.com/phetsims/hookes-law/issues/35

I did this for Molarity, and thought I had also done it for this sim. Thanks for the heads up. Closing!
