### ISSUE TITLE
RC test: Graphing Lines 1.1.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#445]
http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.0-rc.2/graphing-lines_en.html

Fixes made were very localized and not platform specific. So this RC requires spot testing on any 1 platform, and does not require a test matrix.  Instead, there is a short checklist of tests below. Please check these off as they are completed. And please indicate the test platform used (device name and type) in the comments below.

Regression test these issues. If you find a problem, reopen the issue and provide details.

- [x] Timer covered by stringTest=double https://github.com/phetsims/graphing-lines/issues/52
- [x] Grid shown while hide grid checked https://github.com/phetsims/graphing-lines/issues/53
- [x] some saved lines cannot be erased https://github.com/phetsims/graphing-lines/issues/54

Due to changes made for https://github.com/phetsims/graphing-lines/issues/56, the Game should be tested by playing a few dozen challenges.

- [x] Game tested

**Comment by ariel-phet** [comment]
@BryceAG It looks like you are available this afternoon. If so it would be great to polish of this testing so we can redeploy the sim. Thanks!

**Comment by BryceAG** [comment]
Tested on Bates, windows 7. The first 3 regression tests were tested on Chrome, Firefox, and Internet Explorer. The game was tested several dozen times on Chrome only, although I was unable to test a game matching the -9/7 slope as was in the screenshot for the initial issue. All questions I was given did accept the correct answer.

**Comment by ariel-phet** [comment]
@pixelzoom - see comment above....seem OK to go ahead with redepoly?

**Comment by pixelzoom** [comment]
Re @BryceAG comment https://github.com/phetsims/tasks/issues/445#issuecomment-162092475 ... The  -9/7 slope is unlikely to ever come up.  But there are undoubtedly other slopes (difficult to identify) that could have this problem.  I'm confident that the floating point error is resolved, but wanted you to test the Game to make sure it wasn't (generally) broken by the changes. So thanks for doing that.

@ariel-phet yes, ready to redeploy, I'll proceed.

**Comment by pixelzoom** [comment]
1.1.0 has been published to the PhET website.  Closing.

**Comment by pixelzoom** [comment]
Remaining redeploy items enumerated in https://github.com/phetsims/graphing-lines/issues/58.
