### ISSUE TITLE
RC Test: Neuron 1.0.0-rc.3

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#509]
This should be a full retest, since some of the changes affected the way the simulation is clocked, which could impact performance on all platforms.

**Test Matrix**
https://docs.google.com/spreadsheets/d/13lSN1kUHkqDnar9EkoMerj-WCuVfxAZwnqgxjUGTSe0/edit#gid=1112106199

**Issues to Verify**
The following issues should be verified as fixed or at least addressed (these were logged during testing of 1.0.0-rc.2):

*Please read through the issue resolution before testing so that there are no misunderstandings about the expected behavior.*

- [x] Concentrations Blow Up in Firefox (win 7), https://github.com/phetsims/neuron/issues/114
- [x] Potential chart affected by zooming during neuron stimulation, https://github.com/phetsims/neuron/issues/109
- [x] Neuron disappears in IE11 with Win 8, https://github.com/phetsims/neuron/issues/108

**Comment by jbphet** [comment]
Test matrix: https://docs.google.com/spreadsheets/d/13lSN1kUHkqDnar9EkoMerj-WCuVfxAZwnqgxjUGTSe0/edit#gid=1112106199

**Comment by phet-steele** [comment]
@jbphet the dialogue for webgl context loss correctly appears in this rc.

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @brroberts1231 @orejolaphet @elisemorgan please make this your current top testing priority

**Comment by elisemorgan** [comment]
Testing is complete

**Comment by jbphet** [comment]
Excellent - thanks everyone.  I'll close this and address the issues found.
