### ISSUE TITLE
RC test: Ohm's Law 1.3.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#516]
Ohm's Law 1.3.0-rc.1 is ready for testing.

**NOTE**
Please do a full test on all platforms, but be aware that the priority for this release is making the sim translatable. We will be doing several of these kinds of tests, mainly addressing the translation issues

**So before you test** look over the known issues in the sim.

**Test Matrix**
https://docs.google.com/spreadsheets/d/1ADXBLeL4OlX9kvc-oEUb6lkCVh1k0dkf_p_LIfzG2k4/edit#gid=973826419

Please verify that the following issues are fixed:

- [x] Issues with Double, Long, rtl String Tests (https://github.com/phetsims/ohms-law/issues/47)
- [ ] Simulation is unresponsive on Microsoft Edge (https://github.com/phetsims/ohms-law/issues/46)
- [x] Issue "?stringTest=double" text overlap (https://github.com/phetsims/ohms-law/issues/40)

Also please retest this one, which may or may not be resolved:
- [ ] Artifacts occur sometimes around the "R" (https://github.com/phetsims/ohms-law/issues/26)

If you discover a non-translation problem, and it is not a known issue, please create a new issue and reference it to this test.

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @brroberts1231 @orejolaphet @elisemorgan @phet-steele please currently make this the next testing priority in the queue after Balloons and Static electricity

**Comment by ariel-phet** [comment]
Moving to medium priority. Current priority list should go Balloons, Gravity Force lab dev test, and then this test.

**Comment by jbphet** [comment]
A new RC is needed due to some issues with the latest version of Edge, see https://github.com/phetsims/scenery/issues/515.  Closing this one, rolling a new RC.
