### ISSUE TITLE
Dev Test Gravity Force Lab V-2.0.0-dev.2

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#517]
The dev version of Gravity Force Lab is out and is [here](http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.0.0-dev.2/gravity-force-lab_en.html)

This version fixes the issues brought up in last testing. Besides this a new feature is added of constant mass in it. The code has gone through lot of refactoring and will require thorough testing.

**Issues to test for**

- [x] Resetting when masses are touching (https://github.com/phetsims/gravity-force-lab/issues/45)
- [x] Ruler exits screen bounds (https://github.com/phetsims/gravity-force-lab/issues/44)
- [x] iPad left and right bounds (https://github.com/phetsims/gravity-force-lab/issues/43)
- [x] Extreme Left and Right Behaviour (https://github.com/phetsims/gravity-force-lab/issues/42)
- [ ] Text Issues on iOS 9 HTML download (https://github.com/phetsims/gravity-force-lab/issues/41)

**New Feature**

- [x] Constant Radius masses radius doesn't change but color density changes

**Platforms**
Please test on the following (and not in issue the platform you are claiming)

- [x] iPad2 iOS 9+
- [x] Windows Chrome
- [x] Windows Edge
- [x] Mac Safari

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @brroberts1231 @orejolaphet @elisemorgan @phet-steele please make this the next testing priority after the completion of #513

**Comment by BryceAG** [comment]
Testing Win Chrome

**Comment by brroberts1231** [comment]
Safari

**Comment by elisemorgan** [comment]
iPad 2

**Comment by elisemorgan** [comment]
Dev testing is complete

**Comment by ariel-phet** [comment]
@elisemorgan there appear to be two unchecked items above?

**Comment by elisemorgan** [comment]
Text issues was tested but is not resolved. Wasn't sure whether or not to check it.

**Comment by ariel-phet** [comment]
@elisemorgan and the constant radius?

**Comment by elisemorgan** [comment]
@ariel-phet no issues with that feature

**Comment by ariel-phet** [comment]
thanks, closing
