### ISSUE TITLE
RC Test: Neuron 1.0.0-rc.5

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#522]
Neuron 1.0.0-rc.5 is ready for testing.  This version was created due to a couple of issues with the previous RC when running on the latest version of Edge.  A full retest is not required, but a sanity test (i.e. a test to make sure that it loads, runs, and is interactive) should be done on our major platforms.  Please sanity test on:

- [x] Windows 7 + Chrome
- [x] Windows 10 + Chrome
- [x] Windows 7 or 10 + Firefox
- [x] Mac OSX + Safari 10.x
- [x] iPad 2 + iOS 9.2

Please do a full test on:
- [x] Windows 10 + Edge (preferably Edge 25)

Please verify that the following issues are resolved and update the issue in GitHub:
- [x] Neuron patches for scenery (https://github.com/phetsims/neuron/issues/120)
- [x] Stimulating after the chart completes instantiates more stimuli than desired (https://github.com/phetsims/neuron/issues/118)
- [x] Concentrations don't reset (https://github.com/phetsims/neuron/issues/117)

Link to the RC: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.5/neuron_en.html

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @brroberts1231 @orejolaphet @elisemorgan @phet-steele please currently make this the next testing priority in the queue after #520

**Comment by ariel-phet** [comment]
Also if you take the windows edge test, please not in the issue

**Comment by brroberts1231** [comment]
Taking Edge

**Comment by brroberts1231** [comment]
Appears to run correctly now on Edge. phetsims/neuron#120 scenery issue not recreated.

**Comment by ariel-phet** [comment]
testing complete closing
