### ISSUE TITLE
RC Test: Resistance in a Wire 1.2.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#528]
This is the first release candidate for the translatable version of this simulation, so a full retest should be performed.

**Test Matrix**
https://docs.google.com/spreadsheets/d/1vKzKed4O0Dh19_2eNDCabfxRCnJKERNixUqt7jQ_xWE/edit#gid=2107416879

**Issues to Verify**
The following issues should be verified, and if fixed, please close the issue.  *Please also read through the issue resolution before testing so that there are no misunderstandings about the expected behavior.*

- [ ] make symbols translatable (https://github.com/phetsims/resistance-in-a-wire/issues/43)
- [ ] i18n issues in SliderBox (https://github.com/phetsims/resistance-in-a-wire/issues/59)
- [ ] Issues with Long, rtl String Tests (https://github.com/phetsims/resistance-in-a-wire/issues/63)
- [ ] Layout tweaks (https://github.com/phetsims/resistance-in-a-wire/issues/65)
- [ ] clipping not working on Edge 20 (https://github.com/phetsims/resistance-in-a-wire/issues/68)
- [ ] text artifact on Edge (https://github.com/phetsims/resistance-in-a-wire/issues/69)

**Redeploy General Tests**
The following tests should also be performed as part of this testing
- [ ] stringTest=double
- [ ] stringTest=long
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [ ] showPointerAreas (touchArea=red, mouseArea=blue)
- [ ] Full screen test
- [ ] Reference issues to RC test task

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @brroberts1231 @orejolaphet @elisemorgan @phet-steele please makes this the next testing priority after #526 is complete

**Comment by jbphet** [comment]
Two issues were logged during the early testing on this, and I've fixed them, so I'm going to roll a new RC and create a new test task.  Closing this one.
