### ISSUE TITLE
RC Test: Resistance in a Wire 1.2.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#531]
This is the second release candidate for the translatable version of this simulation, but I cut short the first round in order to fix a couple of issues, so a full retest should be performed.

**Test Matrix**
https://docs.google.com/spreadsheets/d/1vKzKed4O0Dh19_2eNDCabfxRCnJKERNixUqt7jQ_xWE/edit#gid=72714242

**Issues to Verify**
The following issues should be verified, and if fixed, please close the issue.  *Please also read through the issue resolution before testing so that there are no misunderstandings about the expected behavior.*

- [x] make symbols translatable (https://github.com/phetsims/resistance-in-a-wire/issues/43)
- [x] i18n issues in SliderBox (https://github.com/phetsims/resistance-in-a-wire/issues/59)
- [x] Issues with String Tests (https://github.com/phetsims/resistance-in-a-wire/issues/63)
- [x] Layout tweaks (https://github.com/phetsims/resistance-in-a-wire/issues/65)
- [x] clipping not working on Edge 20 (https://github.com/phetsims/resistance-in-a-wire/issues/68)
- [x] text artifact on Edge (https://github.com/phetsims/resistance-in-a-wire/issues/69)
- [x] Rtl causes no symbols to be in equation, and causes IE11 to crash (https://github.com/phetsims/resistance-in-a-wire/issues/71)

**Redeploy General Tests**
The following tests should also be performed as part of this testing
- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [x] Full screen test
- [x] Reference issues to RC test task

**Comment by ariel-phet** [comment]
@BryceAG @bryo5363 @brroberts1231 @orejolaphet @elisemorgan @phet-steele please makes this the next priority after #526

**Comment by ariel-phet** [comment]
Moving to top priority now that WOAS testing is complete

**Comment by phet-steele** [comment]
@jbphet @ariel-phet finito

**Comment by ariel-phet** [comment]
test task complete, closing
