### ISSUE TITLE
RC Test: Balancing Act 1.1.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#544]
Balancing Act 1.1.0-rc.1 is ready for testing.

**Test Link:** http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.1.0-rc.1/balancing-act_en.html

**Link to test matrix:** https://docs.google.com/spreadsheets/d/1FM9JxwMp_HSZFeUWDY4gWaUmQ0TOSOtVMqyVuYesPpw/edit#gid=2

Please do a full test of this RC on all platforms, and run the following to check internationalization:

- [x] stringTest=double
- [x] stringTest=long
- [x] stringTest=x
- [x] stringTest=rtl
- [x] stringTest=xss (should not redirect, OK to look bad, test on one desktop platform)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Reference issues to RC test task

Please test the following open issues and close them if they are fixed:

- [x] ?stringTest=double issues (https://github.com/phetsims/balancing-act/issues/60)
- [x] Issue "?stringTest=double" covering objects (https://github.com/phetsims/balancing-act/issues/47)
- [x] carousel buttons very light (https://github.com/phetsims/balancing-act/issues/37)
- [x] Icons on home screen don't look very good on Firefox 27 and IE11 (https://github.com/phetsims/balancing-act/issues/9)

Also, please try to duplicate this one and update it if you can, close it if not:
- [x] fuzzMouse Behavior: Caught Objects Don't Stop

The primary purpose of this release is to make the sim translatable, and several other fixes and various code cleanup was also performed, so thorough testing is warranted.

**Comment by ariel-phet** [comment]
@BryceAG @brroberts1231 @elisemorgan @bryo5363 @phet-steele next in line for redepoly testing after #543

**Comment by phet-steele** [comment]
@jbphet testing for this rc is done.

**Comment by jbphet** [comment]
Thanks for the testing.  I'll work on the open issues and put out a new RC shortly.  Closing.
