### ISSUE TITLE
RC Test: Gravity Force Lab 2.0.0-rc.2

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#551]
Gravity Force Lab 2.0.0-rc.2
**Test Link** : http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.0.0-rc.2/gravity-force-lab_en.html

A few minor bugs were discovered in 2.0.0-rc.1 and does not requires complete re-testing. These issues were fixed and should be verified:

- [x] Slider track should be black (https://github.com/phetsims/gravity-force-lab/issues/71)
- [x] Labels on slider appear clickable (https://github.com/phetsims/gravity-force-lab/issues/70)
- [x] Mass gradient doesn't update as mass resizes (https://github.com/phetsims/gravity-force-lab/issues/69)
- [x] Mass Gradient (https://github.com/phetsims/gravity-force-lab/issues/68)
- [x] Panel Capitalization is inconsistent (https://github.com/phetsims/gravity-force-lab/issues/67)
- [x] Add AP and AR to "team" credits (https://github.com/phetsims/gravity-force-lab/issues/66)

Also please try to duplicate this one and if can't close the issue. As we think it might have been fixed because of some changes we did but not sure of that 
- [x] Text Issues on iOS 9 HTML download (https://github.com/phetsims/gravity-force-lab/issues/41)

**Comment by ariel-phet** [comment]
I am testing currently, will do this myself

**Comment by ariel-phet** [comment]
All issues resolved! @aadish, @jbphet  looks like this sim is ready for redeploy

**Comment by aadish** [comment]
thanks @ariel-phet for testing this, 
closing the issue and the sim has been deployed and is live on the website
