### ISSUE TITLE
RC Test: Build An Atom 1.2.0-rc.2

### ISSUE THREAD

**Issue by aadish** [phetsims/tasks#581]
Issues

 from rc.1 are verified and fixed, and rc.2 is ready for testing.

**Link to the sim**: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.2.0-rc.2/build-an-atom_en.html

**Link to IFrame**: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.2.0-rc.2/build-an-atom_en-iframe.html

There were only a few changes since v1.2.0-rc.1, so a full retest is not required. Please do a sanity test on the major supported platforms, then verify that the following have been fully fixed (and close them if so):
 
- [x] 1st Level selection image needs to be updated https://github.com/phetsims/build-an-atom/issues/129
- [x] Games don't end well after Refresh button is clicked https://github.com/phetsims/build-an-atom/issues/128
- [x] Continue button doesn't appear after game is completed https://github.com/phetsims/build-an-atom/issues/127
- [x] Score does not refresh when page is refreshed https://github.com/phetsims/build-an-atom/issues/126

**Comment by ariel-phet** [comment]
@phet-steele @elisemorgan @brroberts1231 @BryceAG @bryo5363 please make this the current top testing priority, would be good to finish off and get republished!

**Comment by phet-steele** [comment]
Works fine on Win 10 and iPads.

**Comment by aadish** [comment]
@phet-steele thanks for testing this, the sim has been deployed and it is live, closing it
