### ISSUE TITLE
RC Test: Area Builder 1.1.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#593]
Area Builder 1.1.0-rc.2 is ready for release candidate testing.

Link to sim: http://www.colorado.edu/physics/phet/dev/html/area-builder/1.1.0-rc.2/area-builder_en.html

Link to iframe: http://www.colorado.edu/physics/phet/dev/html/area-builder/1.1.0-rc.2/area-builder_en-iframe.html

There were only a few issues identified during the testing of 1.1.0-rc.1, and those issues should be addressed in this release, so a full re-test is not required.  My recommendation is to perform basic sanity testing on the primary supported platforms, and then verify that the following issues are addressed, closing them if so, updating them if not:

- [x] Text box issues with stringTest=double https://github.com/phetsims/area-builder/issues/87
- [x] Perimeter label encroaches upon the Values panel https://github.com/phetsims/area-builder/issues/94
- [x] Held objects slide while scrolling the carousel https://github.com/phetsims/area-builder/issues/95
- [x] Add Amanda Davis to QA credits https://github.com/phetsims/area-builder/issues/96
- [x] Poor rendering of happy face in game home screen game Icon https://github.com/phetsims/area-builder/issues/68

**Comment by ariel-phet** [comment]
@phet-steele looks like you are all over this already

**Comment by phet-steele** [comment]
@ariel-phet @jbphet things look fine on Win 10 Chrome/FF, Mac Safari OSX 10.11.4, and iOS 9.3.2.

**Comment by jbphet** [comment]
Thanks for the testing, it has now been published.  Closing.
