### ISSUE TITLE
Testing for Circuit Construction Kit: Black Box Study 1.0.0-dev.19

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#643]
Published here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.19/circuit-construction-kit-black-box-study_en.html

This version fixes issues identified in previous versions.  Here are the issues to be verified:

- [x] Vertex becomes dislocated when joining after an auto-move https://github.com/phetsims/circuit-construction-kit-common/issues/173
- [x] Near-horizontal and near-vertical circuit components flicker near black box vertices https://github.com/phetsims/circuit-construction-kit-common/issues/166
- [x] Electron gaps with short wires https://github.com/phetsims/circuit-construction-kit-common/issues/159
- [x] Much slower performance than dev.17 https://github.com/phetsims/circuit-construction-kit-common/issues/158
- [x] Vertices don't connect in build screen https://github.com/phetsims/circuit-construction-kit-common/issues/141

Exhaustive cross-platform testing is *not* needed at this time, I would mainly like to know if the above issues are resolved and if their solutions have caused any other problems.

@ariel-phet can you prioritize and reassign for testing?

**Comment by phet-steele** [comment]
@samreid done a good amount here, considering it done. I look forward to the next version!

**Comment by phet-steele** [comment]
@samreid I'm going ahead and closing this.

**Comment by samreid** [comment]
Thanks!
