### ISSUE TITLE
Dev test: Charges and Fields 1.0.0-dev.17

### ISSUE THREAD

**Issue by andrewadare** [phetsims/tasks#673]
Testing link:
http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-dev.17/charges-and-fields_en.html

- [x] phetsims/charges-and-fields/issues/46
- [x] phetsims/charges-and-fields/issues/64
- [x] phetsims/charges-and-fields/issues/77
- [x] phetsims/charges-and-fields/issues/81
- [x] phetsims/charges-and-fields/issues/82
- [x] phetsims/charges-and-fields/issues/84
- [x] phetsims/charges-and-fields/issues/85

**Comment by phet-steele** [comment]
Next dev is in the testing queue. Moving to that one.
