### ISSUE TITLE
dev test: States of Matter 1.0.0-dev.14

### ISSUE THREAD

**Issue by jbphet** [phetsims/tasks#725]
States of Matter is ready for some dev testing.  A lot of code has been changed, so a thorough test is needed.  

Also, there are currently 8 issues labeled "fixed-pending-testing" in the issues section of the repo, please test these and close or update.

- [x] phetsims/states-of-matter/issues/169
- [x] phetsims/states-of-matter/issues/167
- [x] phetsims/states-of-matter/issues/166
- [x] phetsims/states-of-matter/issues/165
- [x] phetsims/states-of-matter/issues/164
- [x] phetsims/states-of-matter/issues/161
- [x] phetsims/states-of-matter/issues/154
- [x] phetsims/states-of-matter/issues/150

</br>
Platforms:

- [x] Mac Safari
- [x] Win 10 Edge
- [x] Chrome
- [x] iPad 2

link: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.14/states-of-matter_en.html

**Comment by ariel-phet** [comment]
@phet-steele can you put a checklist of platforms in the first comment as well as related issues to be checked?

**Comment by ariel-phet** [comment]
@phet-steele bumping down to high since GAO testing is definitely top priority, but would be great if this testing could be finished in parallel (or soon after)

**Comment by phet-steele** [comment]
@jbphet this testing is complete.

**Comment by jbphet** [comment]
Thanks, closing.
