### ISSUE TITLE
RC Testing for Energy Skate Park: Basics PhET-iO version 1.3.0-phetiorc.1

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#763]
See https://github.com/phetsims/phet-io/issues/533

This version implements the ability to save and load tracks using the PhET-iO API, which can be demonstrated/tested in the state wrapper.

The RC is published here:
http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.3.0-phetiorc.1/wrappers/index/

Testing Matrix: https://docs.google.com/spreadsheets/d/1kaJd59mURbe9tPcHZsJPRXZH2yU9jm_AjsdPSmojTcc/edit#gid=1465709620

This version will replace the former version *and* has been developed in master, so all wrappers and the simulation itself need to be tested on our usual cross-platform list using @phet-steele's latest procedure for thoroughly testing phet-io simulations.

Please be aware of pre-existing issues in the PhET-iO instrumented simulation which have not been addressed, searchable through the phet-io issues.

For any new issues that are reported, please indicate (a) whether it is also problematic in the prior version https://phet-io.colorado.edu/sims/energy-skate-park-basics/1.2.3-phetio/wrappers/index/ as well as (b) the severity of the issue and your opinion as to whether it warrants another RC cycle.

Assigning to @ariel-phet for priority and assignment.  @kathy-phet requested this to be ready to deliver to BrainPOP on or before January 30, 2017.

**Comment by kathy-phet** [comment]
Just a note: While "on or before Jan 30" is what we committed to, they would use if as soon as it is delivered and it is holding up their work. So relatively high priority --- behind PhET App and behind Make-a-Ten.

**Comment by ariel-phet** [comment]
Given the short timeline on which hope to deliver, making this current top test priority

**Comment by samreid** [comment]
@phet-steele and @ariel-phet what is the status on this issue?

**Comment by ariel-phet** [comment]
@samreid - @phet-steele was actively testing yesterday and as noted it is the top testing priority currently, so it will be worked on until it is finished

**Comment by phet-steele** [comment]
@samreid testing here is done, back to you!

**Comment by samreid** [comment]
Many thanks @phet-steele and @EthanWJohnson, I've fixed some of the issues in master + branch, will leave this issue open to track fixing them all in the branch.

**Comment by samreid** [comment]
@zepumph let's work together at your convenience to move your fixes from master to these stable branches for the next release.

**Comment by zepumph** [comment]
I cherry picked these commits: 

https://github.com/phetsims/joist/commit/eadf3020fc44920dd7a855f183432e58458a995d to joist
https://github.com/phetsims/phet-io/commit/e9ddcece2776022c6d2c2c3711c15d245c3f2e06 to phet-io
https://github.com/phetsims/chipper/commit/24125355349a8296d589d9b436f3a3654e65d8e2 to chipper
https://github.com/phetsims/chipper/commit/5f37f55ed6bafcc8acf0798099bbf8b4cff0c12b to chipper

into branch: energy-skate-park-basics-1.3-phetio in respective repos. 

These commits are from these issues:
phetsims/phet-io#969
phetsims/phet-io#974
phetsims/phet-io#978

I believe this is all of the fix I have caused for this issue. Let me know if I can be of more assistance.

**Comment by zepumph** [comment]
I then updated the dependencies from a build I did with everything checked out. Unassigning myself.

**Comment by samreid** [comment]
Thanks @zepumph, I'll make a table of the fixes and we can see which still need to get cherry picked.

- [ ] devguide.html fails to style the page phetsims/phet-io#969
- [ ] [ESPB] Mirror Inputs and all Event wrappers fail at the Barrier Rectangle phetsims/phet-io#974
- [ ] [ESPB] Relative path in Generate HTML phetsims/phet-io#978
- [ ] [ESPB] Gravity Property on all three screens crashes wrapper when set to 0 phetsims/phet-io#984
- [] [ESPB] Skater properties not working well phetsims/phet-io#806
- [ ] [ESPB] Cutting a track loses customization phetsims/phet-io#987
- [ ] [ESPB] seed is being set to null in Mirror Inputs phetsims/phet-io#987

**Comment by samreid** [comment]
It looks like everything is here.  I know @kathy-phet wanted this to be done quickly for BrainPOP so I'll try to publish a new RC soon.

**Comment by samreid** [comment]
I checked out shas, then got the branch for:
chipper
joist
phet-io

**Comment by samreid** [comment]
New version is here, I'll try to spot test the above before creating a new RC issue:
http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.3.0-phetiorc.2/wrappers/index/

**Comment by samreid** [comment]
- [ ] devguide.html fails to style the page phetsims/phet-io#969
- [ ] [ESPB] Mirror Inputs and all Event wrappers fail at the Barrier Rectangle phetsims/phet-io#974
- [ ] [ESPB] Relative path in Generate HTML phetsims/phet-io#978
- [ ] [ESPB] Gravity Property on all three screens crashes wrapper when set to 0 phetsims/phet-io#984
- [ ] [ESPB] Skater properties not working well phetsims/phet-io#806
- [ ] [ESPB] Cutting a track loses customization phetsims/phet-io#987
- [ ] [ESPB] seed is being set to null in Mirror Inputs phetsims/phet-io#987

**Comment by samreid** [comment]
Everything checks out, new RC task coming up.

**Comment by ariel-phet** [comment]
Closing this issue since a new RC task has been made
