### ISSUE TITLE
RC Testing for Energy Skate Park: Basics PhET-iO version 1.3.0-phetiorc.2

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#768]
From #763 

New version is here:
http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.3.0-phetiorc.2/wrappers/index/

To verify:
- [x] devguide.html fails to style the page phetsims/phet-io#969
- [x] [ESPB] Mirror Inputs and all Event wrappers fail at the Barrier Rectangle phetsims/phet-io#974
- [x] [ESPB] Relative path in Generate HTML phetsims/phet-io#978
- [x] [ESPB] Gravity Property on all three screens crashes wrapper when set to 0 phetsims/phet-io#984
- [x] [ESPB] Cutting a track loses customization phetsims/phet-io#987
- [x] Brief checks (one platform) to make sure nothing else was disturbed during these fixes.

Assigning to @ariel-phet for priority and scheduling, and a reminder that @kathy-phet wanted to produce this for BrainPOP relatively soon.

**Comment by ariel-phet** [comment]
@phet-steele given the time pressure on this item, bumping to current top priority

**Comment by phet-steele** [comment]
@samreid the above issues are verified, all on macOS 10.12.3 Chrome (and a dab into Safari).

**Comment by samreid** [comment]
Thanks, I'll move forward with publishing this as a production version.

**Comment by samreid** [comment]
Deployed here: https://phet-io.colorado.edu/sims/energy-skate-park-basics/1.3.0-phetio/wrappers/index/

**Comment by samreid** [comment]
I spot checked instance-proxies => generate HTML and the data stream and all seems well.  I'll share the link to BrainPOP, closing.
