### ISSUE TITLE
RC Testing for Make a Ten 1.0.0-rc.2

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tasks#788]
@amanda-phet, @bethstade, @ariel-phet, Make a Ten 1.0.0-rc.2 is ready for RC testing.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-rc.2/make-a-ten_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-rc.2/make-a-ten_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1aWJdfQl7BV4-qWiBz-oN-mesnT4_6Eo0wO6l0ss3Oso/edit#gid=1932355591)**

**Please also verify**
- [x] Modal keypad (https://github.com/phetsims/make-a-ten/issues/265)
- [x] Layering changes (https://github.com/phetsims/make-a-ten/issues/266)
- [x] Equals sign reset (https://github.com/phetsims/make-a-ten/issues/267)
- [x] Edit button alignment (https://github.com/phetsims/make-a-ten/issues/268)
- [x] Reset button doesn't intrude into level screen (https://github.com/phetsims/make-a-ten/issues/271)
- [x] Formula background handling (https://github.com/phetsims/make-a-ten/issues/272)

If any new issues are found, please note them in https://github.com/phetsims/make-a-ten/issues and reference this issue.
**(Other potentially useful items)**

Sim-specific query parameters useful for testing:
• `?exploreNumbers=X` - Where X is a list of two numbers separated by a comma. They are used as the initial explore screen numbers

**Comment by ariel-phet** [comment]
@phet-steele since this sim is close to publication it should be top testing priority

**Comment by phet-steele** [comment]
![greenlight](https://cloud.githubusercontent.com/assets/5863899/23375459/b036939c-fce5-11e6-9f7a-77fcd69c8dca.png)

**Comment by jonathanolson** [comment]
@amanda-phet and @ariel-phet, good to deploy to production? (I believe https://github.com/phetsims/make-a-ten/issues/273 should not be a blocking issue).

**Comment by ariel-phet** [comment]
@jonathanolson yes, good to deploy! closing
