### ISSUE TITLE
Confirm changes for profile pages

### ISSUE THREAD

**Issue by mattpen** [phetsims/tasks#915]
@phet-steele - Can QA please confirm that the most recent changes for the profile pages haven't introduced any new bugs?

The issues are:
- [ ] phetsims/website-meteor#48
- [ ] phetsims/website-meteor#49
- [ ] phetsims/website-meteor#50
- [ ] phetsims/website#669

The components affected are the admin page tables for schools/orgs, the Add Your School/Org dialog, the School/Org autosuggest input, and the translator's page for Users.

You can test the changes on ox-dev, they are running in a production state now.

**Comment by mattpen** [comment]
Wrong repo - handled in https://github.com/phetsims/QA/issues/91
